### PR TITLE
Home Page Admin side

### PR DESCRIPTION
**Pull request by InquisitiveMe15**
Screenshot (589)
Screenshot (590)

### CODE REVIEW

**Comment by akashg3627** [comment]
change the file structure to as discussed in our meet
->Profile
   ->Form
      ->Form.js
      ->Form.css
   ->Poster
      ->Poster.js
      ->Poster.css
   ->Logo
      ->Logo.js
      ->Logo.css
->Navbar
    ->Navbar.js
    ->Navbar.css

**Comment by InquisitiveMe15** [comment]
> change the file structure to as discussed in our meet ->Profile ->Form ->Form.js ->Form.css ->Poster ->Poster.js ->Poster.css ->Logo ->Logo.js ->Logo.css ->Navbar ->Navbar.js ->Navbar.css

I have changed the file structure after discussing it with Suman. Kindly see.

**Review by akashg3627 — CHANGES_REQUESTED** [review]
Whats this toboDeleted thing? 
And also once do rebase after pulling

**Comment by InquisitiveMe15** [comment]
> Whats this toboDeleted thing?
The folder has to be deleted. I forgot. Now I have deleted it.

> And also once do rebase after pulling
okay

**Comment by InquisitiveMe15** [comment]
Bhaiya! check now.

**Review by akashg3627 — APPROVED** [review]

**Pull request merged**
